/* @flow */

const SIGN_IN_IMPLEMENTATION_TREZOR_V1: string = 'trezor/v1'
const SIGN_IN_IMPLEMENTATION_TREZOR_V2: string = 'trezor/v2'

const SIGN_IN_IMPLEMENTATIONS: Array<string> = [
  SIGN_IN_IMPLEMENTATION_TREZOR_V1,
  SIGN_IN_IMPLEMENTATION_TREZOR_V2
]

module.exports = {
  SIGN_IN_IMPLEMENTATION_TREZOR_V1,
  SIGN_IN_IMPLEMENTATION_TREZOR_V2,
  SIGN_IN_IMPLEMENTATIONS
}
