const SIGN_IN_IMPLEMENTATION_TREZOR_V1 = 'trezor/v1'
const SIGN_IN_IMPLEMENTATION_TREZOR_V2 = 'trezor/v2'

const SIGN_IN_IMPLEMENTATIONS = [
  SIGN_IN_IMPLEMENTATION_TREZOR_V1,
  SIGN_IN_IMPLEMENTATION_TREZOR_V2
]

module.exports = {
  SIGN_IN_IMPLEMENTATION_TREZOR_V1,
  SIGN_IN_IMPLEMENTATION_TREZOR_V2,
  SIGN_IN_IMPLEMENTATIONS
}
